name: Build All
on:
  pull_request:
  merge_group:
  schedule:
    - cron: '0 0 * * Sun'  # at 12:00 am Sunday
  workflow_dispatch:

jobs:

  # build oci container image
  job-build:
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      fail-fast: false
    uses: ./.github/workflows/build.yml
    secrets: inherit

  # remove old images
  job-clean-images:
    needs: job-build-system
    uses: ./.github/workflows/cleanup.yml
    secrets: inherit
